application: retweetretract
version: 1
runtime: go
api_version: go1

handlers:
- url: /fonts
  static_dir: fonts

- url: /sass
  static_dir: sass

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: _go_app
